numbers = [2, 4, 8, 16, 32, 64, 128]
sum_nums = sum(numbers)
product = eval('*'.join(map(str, numbers)))
binary_sum = bin(sum_nums)
print(f'Sum: {sum_nums}')
print(f'Product: {product:,}')
print(f'Binary of sum: {binary_sum}')
print('Interesting fact:')
print('- These are consecutive powers of 2 from 2^1 to 2^7')
print(f'- Their sum is {sum_nums}, which equals {bin(sum_nums)} (one less than the next power of 2)')
print(f'- The product would be astronomically large: {product:,}')